version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: fullstacks
    ports:
      - 5432:5432
    volumes:
      - fullstacks:/var/lib/postgresql/data
volumes:
  fullstacks: